In [1]:
import numpy as np
data = np.load("unbounded_polyhedron.npz")

A = data["A"]
b = data["b"]

In [2]:
import mpc_tools.geometry as geo
from scipy.optimize import nnls

In [3]:
p = geo.Polytope(A, b)

In [4]:
p.assemble()

Infinite Chebyshev center or radius!


ValueError: Unbounded polyhedron: only polytopes allowed

In [6]:
p.empty

False

In [7]:
p.radius

inf

In [8]:
data = np.load("nnls_args.npz")
A_bar = data["A_bar"]
b_bar = data["b_bar"]

In [9]:
nnls(A_bar, b_bar)

(array([  0.00000000e+00,   5.46165584e-12,   2.07983444e-11,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   4.99865214e-01,   0.00000000e+00,
          4.99230514e-01,   5.96498459e-04,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          2.73788640e-12,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   7.95105149e-05,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   5.55000311e-05,
          0.00000000e+00,   0.00000000e+00,   1.17824683e-04,
          3.62881980e-09,   0.00000000e+00,   5.49340436e-05,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
        

In [6]:
import cdd
def cdd_vertices(A, b, number_type="float"):
    b = b.reshape((-1, 1))
    inequality_list = np.hstack((b, -A)).tolist()
    inequality_matrix = cdd.Matrix(inequality_list, number_type=number_type)
    inequality_matrix.rep_type = cdd.RepType.INEQUALITY
    polyhedron = cdd.Polyhedron(inequality_matrix)
    generator_matrix = polyhedron.get_generators()
    generator_list = generator_matrix.__getitem__(slice(0, generator_matrix.row_size))
    vertices = np.vstack([np.array(map(float, generator_list[i][1:])) for i in range(0, len(generator_list)) if generator_list[i][0] == 1])
    return vertices


In [7]:
cdd_vertices(A, b, "float")

array([[ -5.93631886e-15,   1.00403923e-01,  -1.86848069e-14, ...,
         -2.51500000e-01,   1.99994000e-01,   4.04244465e-01],
       [ -7.14926275e-15,   1.00403923e-01,  -1.39972600e-14, ...,
          2.51500000e-01,   1.99994000e-01,   4.04244465e-01],
       [ -4.49633945e-15,   1.00403923e-01,  -2.42638827e-14, ...,
         -2.51500000e-01,   1.99994000e-01,   4.04244465e-01],
       ..., 
       [ -1.23507464e-01,   1.35777871e-01,   4.71716196e-01, ...,
         -2.75227325e-01,  -5.47188035e-01,  -5.48656546e-01],
       [ -1.23507464e-01,   1.35777871e-01,   4.71716196e-01, ...,
          2.27772675e-01,  -5.47188035e-01,  -5.48656546e-01],
       [ -1.23507464e-01,   1.35777871e-01,   4.71716196e-01, ...,
          2.27772675e-01,  -5.47188035e-01,  -5.48656546e-01]])

In [8]:
cdd_vertices(A, b, "fraction")

array([[ -4.97934979e-02,   1.48794444e-01,  -1.21682799e+00, ...,
          3.12706448e-01,  -3.78328550e-01,   5.25979984e-01],
       [ -4.97934979e-02,   2.25880565e-01,  -1.21682799e+00, ...,
          3.12706448e-01,  -3.78328550e-01,   8.34333719e-01],
       [ -5.46218905e-02,   1.45843549e-01,  -1.16317365e+00, ...,
          3.10007635e-01,  -3.83694146e-01,   5.20615327e-01],
       ..., 
       [ -8.55184015e-02,   1.36852057e-01,  -5.12623085e-01, ...,
         -2.25715059e-01,   3.30747463e-03,  -5.20900658e-01],
       [  1.21922913e-01,   1.35627077e-01,  -4.65664265e-01, ...,
         -2.28077087e-01,   3.97267481e-01,  -5.48958144e-01],
       [ -8.69564764e-02,   1.37067769e-01,  -5.21243339e-01, ...,
         -2.25281460e-01,   6.50950172e-13,  -5.20038606e-01]])