In [1]:
using Polyhedra
using CDDLib
using ConvexHull
using QHull

In [2]:
A = readdlm("A.txt")

32×12 Array{Float64,2}:
  0.0   0.0   0.0          0.0   0.0  …   1.0   0.0        0.0   0.0      
  0.0   0.0   0.0          0.0   0.0     -1.0   0.0        0.0   0.0      
  0.0   0.0   0.0          0.0   0.0      0.0   0.0        1.0   0.0      
  0.0   0.0   0.0          0.0   0.0      0.0   0.0       -1.0   0.0      
  1.0   0.0   0.0          0.0   0.0      0.0   0.0        0.0   0.0      
 -1.0   0.0   0.0          0.0   0.0  …   0.0   0.0        0.0   0.0      
  0.0   0.0   0.0          0.0   1.0      0.0   0.0        0.0   0.0      
  0.0   0.0   0.0          0.0  -1.0      0.0   0.0        0.0   0.0      
  0.0   0.0   0.0          0.0   0.0      0.0   1.0        0.0   0.0      
  0.0   0.0   0.0          0.0   0.0      0.0  -1.0        0.0   0.0      
  0.0   0.0   0.0          0.0   0.0  …   0.0   0.0        0.0   1.0      
  0.0   0.0   0.0          0.0   0.0      0.0   0.0        0.0  -1.0      
  0.0   0.0   1.0          0.0   0.0      0.0   0.0        0.0   0.0      
 

In [3]:
b = vec(readdlm("b.txt"))

32-element Array{Float64,1}:
  1.0     
  1.0     
 10.0     
 10.0     
  5.0     
  5.0     
 10.0     
 10.0     
  1.0     
  1.0     
 10.0     
 10.0     
  5.0     
  ⋮       
  5.0     
  5.0     
 10.0     
 10.0     
  0.998749
  0.998749
  9.95037 
  9.95037 
  5.0     
  5.0     
 10.0     
 10.0     

In [4]:
h = SimpleHRepresentation(A, b);

In [5]:
p = polyhedron(h, CDDLibrary(:exact))
SimpleVRepresentation(vrep(p)).V

16384×12 Array{Rational{BigInt},2}:
 32//7169998590479189  -5//1  32//7169998590479189  -5//1  …  -10//1  -10//1
  5//1                 -5//1  32//7169998590479189  -5//1     -10//1  -10//1
 32//7169998590479189  -5//1   5//1                 -5//1     -10//1  -10//1
  5//1                 -5//1   5//1                 -5//1     -10//1  -10//1
 32//7169998590479189  -5//1  32//7169998590479189  -5//1     -10//1  -10//1
  5//1                 -5//1  32//7169998590479189  -5//1  …  -10//1  -10//1
 32//7169998590479189  -5//1   5//1                 -5//1     -10//1  -10//1
  5//1                 -5//1   5//1                 -5//1     -10//1  -10//1
 32//7169998590479189  -5//1  32//7169998590479189  -5//1     -10//1  -10//1
  5//1                 -5//1  32//7169998590479189  -5//1     -10//1  -10//1
 32//7169998590479189  -5//1   5//1                 -5//1  …  -10//1  -10//1
  5//1                 -5//1   5//1                 -5//1     -10//1  -10//1
 32//7169998590479189  -5//1  32//716999

In [6]:
p = polyhedron(h, CDDLibrary(:float))
v = SimpleVRepresentation(vrep(p)).V

16384×12 Array{Float64,2}:
  9.52571e-15  -5.0   9.02237e-15  -5.0  …  -0.5     -0.5     -10.0  -10.0
  5.0          -5.0   2.57269e-15  -5.0     -0.5125  -0.5     -10.0  -10.0
  2.79601e-14  -5.0   5.0          -5.0     -0.5     -0.5125  -10.0  -10.0
  5.0          -5.0   5.0          -5.0     -0.5125  -0.5125  -10.0  -10.0
 -4.44089e-16  -5.0   1.10953e-15  -5.0      1.0     -0.5     -10.0  -10.0
  5.0          -5.0  -2.79293e-15  -5.0  …   1.0     -0.5     -10.0  -10.0
  0.0          -5.0   5.0          -5.0      1.0     -0.5125  -10.0  -10.0
  5.0          -5.0   5.0          -5.0      1.0     -0.5125  -10.0  -10.0
  1.10953e-14  -5.0  -1.06536e-14  -5.0     -0.5      1.0     -10.0  -10.0
  5.0          -5.0  -5.88192e-15  -5.0     -0.5125   1.0     -10.0  -10.0
  1.33143e-15  -5.0   5.0          -5.0  …  -0.5      1.0     -10.0  -10.0
  5.0          -5.0   5.0          -5.0     -0.5125   1.0     -10.0  -10.0
  0.0          -5.0  -5.55112e-15  -5.0      1.0      1.0     -10.0  -10.

In [7]:
p = polyhedron(h, QHullLib())
SimpleVRepresentation(vrep(p)).V

16384×12 Array{Float64,2}:
 -5.0  -5.0  -5.0  -5.0  -10.0  -10.0  …  1.0      1.0       0.25   -9.5 
 -5.0  -5.0   0.0  -5.0  -10.0  -10.0     1.0      1.0       0.25  -10.0 
 -5.0  -5.0  -5.0  -5.0  -10.0  -10.0     0.5125   1.0      10.0    -9.5 
 -5.0  -5.0   0.0  -5.0  -10.0  -10.0     0.5125   1.0      10.0   -10.0 
  5.0  -5.0  -5.0  -5.0  -10.0  -10.0     1.0      1.0      -0.25   -9.5 
  5.0  -5.0   0.0  -5.0  -10.0  -10.0  …  1.0      1.0      -0.25  -10.0 
  5.0  -5.0  -5.0  -5.0  -10.0  -10.0     1.0      1.0     -10.0    -9.5 
  5.0  -5.0   0.0  -5.0  -10.0  -10.0     1.0      1.0     -10.0   -10.0 
 -5.0  -5.0  -5.0  -5.0  -10.0  -10.0     1.0     -1.0       0.25   10.0 
 -5.0  -5.0  -5.0  -5.0  -10.0  -10.0     0.5125  -1.0      10.0    10.0 
  5.0  -5.0  -5.0  -5.0  -10.0  -10.0  …  1.0     -1.0      -0.25   10.0 
  5.0  -5.0  -5.0  -5.0  -10.0  -10.0     1.0     -1.0     -10.0    10.0 
 -5.0  -5.0  -5.0  -5.0  -10.0  -10.0     1.0      1.0      -9.5    -9.5 
  ⋮        

In [35]:
interior_point = vec(readdlm("interior_point.txt"))

12-element Array{Float64,1}:
  4.00125   
 -4.00125   
 -4.00125   
 -4.00125   
 -9.00125   
 -9.00125   
 -9.00125   
 -9.00125   
 -0.00125074
  0.00125074
 -0.175047  
  0.175047  

In [38]:
b

32-element Array{Float64,1}:
  1.0     
  1.0     
 10.0     
 10.0     
  5.0     
  5.0     
 10.0     
 10.0     
  1.0     
  1.0     
 10.0     
 10.0     
  5.0     
  ⋮       
  5.0     
  5.0     
 10.0     
 10.0     
  0.998749
  0.998749
  9.95037 
  9.95037 
  5.0     
  5.0     
 10.0     
 10.0     

In [43]:
all(A * zeros(size(A, 2)) .<= b)

true

In [44]:
maximum(A * interior_point - b)

-0.998749194618989

In [45]:
maximum(A * zeros(size(A, 2)) - b)

-0.9987492255746373

In [37]:
A * interior_point - b

32-element Array{Float64,1}:
  -1.00125 
  -0.998749
 -10.175   
  -9.82495 
  -0.998749
  -9.00125 
 -19.0013  
  -0.998749
  -0.998749
  -1.00125 
  -9.82495 
 -10.175   
  -9.00125 
   ⋮       
  -9.00125 
  -0.998749
 -19.0013  
  -0.998749
  -0.998749
  -0.998749
 -10.1743  
  -9.72641 
  -9.00125 
  -0.998749
 -19.0013  
  -0.998749

In [27]:
2^14

16384

In [13]:
p = polyhedron(h, ConvexHullLib(:exact))
SimpleVRepresentation(vrep(p)).V

0×12 Array{Rational{BigInt},2}