In [1]:
?find

search: find findn findnz findin findmin findmax findprev findnext findmin!



```
find(f::Function, A)
```

Return a vector `I` of the linear indexes of `A` where `f(A[I])` returns `true`. If there are no such elements of `A`, find returns an empty array.

```jldoctest
julia> A = [1 2; 3 4]
2×2 Array{Int64,2}:
 1  2
 3  4

julia> find(isodd,A)
2-element Array{Int64,1}:
 1
 2
```

```
find(A)
```

Return a vector of the linear indexes of the non-zeros in `A` (determined by `A[i]!=0`). A common use of this is to convert a boolean array to an array of indexes of the `true` elements. If there are no non-zero elements of `A`, `find` returns an empty array.

```jldoctest
julia> A = [true false; false true]
2×2 Array{Bool,2}:
  true  false
 false   true

julia> find(A)
2-element Array{Int64,1}:
 1
 4
```


In [28]:
function simplify(C)
    C = copy(C)
    num_vars = size(C, 2)
    D = eye(num_vars)
    for j in size(C, 2):-1:(size(C, 2) - size(C, 1) + 1)
        @show C
        nonzeros = find(C[:, j])
        @assert length(nonzeros) == 1
        i = nonzeros[1]
        v = C[i, 1:(j - 1)] ./ -C[i, j]
        @show v
        D = D * [eye(j - 1); v']
        @show D
        C = C[vcat(1:(i - 1), (i + 1):end), :]
        @show C
    end
    D
end
    

simplify (generic function with 1 method)

In [29]:
a = 0.1
b = 0.2
A = [b 0 a -1 0; 0 b 0 a -1]

2×5 Array{Float64,2}:
 0.2  0.0  0.1  -1.0   0.0
 0.0  0.2  0.0   0.1  -1.0

In [30]:
simplify(A)

C = [0.2 0.0 0.1 -1.0 0.0; 0.0 0.2 0.0 0.1 -1.0]
v = [0.0,0.2,0.0,0.1]
D = [1.0 0.0 0.0 0.0; 0.0 1.0 0.0 0.0; 0.0 0.0 1.0 0.0; 0.0 0.0 0.0 1.0; 0.0 0.2 0.0 0.1]
C = [0.2 0.0 0.1 -1.0 0.0]
C = [0.2 0.0 0.1 -1.0 0.0]
v = [0.2,0.0,0.1]
D = [1.0 0.0 0.0; 0.0 1.0 0.0; 0.0 0.0 1.0; 0.2 0.0 0.1; 0.02 0.2 0.01]
C = 


5×3 Array{Float64,2}:
 1.0   0.0  0.0 
 0.0   1.0  0.0 
 0.0   0.0  1.0 
 0.2   0.0  0.1 
 0.02  0.2  0.01